var a=[
  {
      "alwaysShow": "false",
      "children": [
          {
              "alwaysShow": "",
              "code": "newpaymentsDelivery",
              "component": "payment/newpayment",
              "hidden": "",
              "id": 242,
              "meta": "{ \"title\": \"新建付款单\", \"icon\": \"form\", \"roles\": [\"service_finance\"] }",
              "name": "newpaymentsDelivery",
              "order": 1,
              "outLinkUrl": "",
              "parentCode": "paymentsDelivery",
              "path": "newpayment",
              "redirect": "",
              "sysCode": "paymentsDelivery",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "paymentlistDelivery",
              "component": "payment/paymentlist",
              "hidden": "",
              "id": 243,
              "meta": "{ \"title\": \"付款单查询\", \"icon\": \"search\", \"roles\": [\"service_finance\"] }",
              "name": "paymentlistDelivery",
              "order": 2,
              "outLinkUrl": "",
              "parentCode": "paymentsDelivery",
              "path": "paymentlist",
              "redirect": "",
              "sysCode": "paymentsDelivery",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "paymentdetailDelivery",
              "component": "payment/paymentdetail",
              "hidden": "true",
              "id": 244,
              "meta": "{ \"title\": \"付款单详情\", \"icon\": \"form\", \"noCache\": true, \"roles\": [\"service_finance\"] }",
              "name": "paymentdetailDelivery",
              "order": 3,
              "outLinkUrl": "",
              "parentCode": "paymentsDelivery",
              "path": "paymentdetail/:ticketno",
              "redirect": "",
              "sysCode": "paymentsDelivery",
              "tId": 7
          }
      ],
      "code": "paymentsDelivery",
      "component": "Layout",
      "hidden": "false",
      "id": 238,
      "meta": "{ \"title\": \"付款管理\", \"icon\": \"tree\", \"roles\": [\"service_finance\"] }",
      "name": "paymentsDelivery",
      "order": 27,
      "outLinkUrl": "",
      "parentCode": "",
      "path": "/payment",
      "redirect": "/payment/newpayment",
      "sysCode": "paymentsDelivery",
      "tId": 7
  },
  {
      "alwaysShow": "",
      "children": [
          {
              "alwaysShow": "",
              "code": "newreceivableDelivery",
              "component": "receivable/newreceivable",
              "hidden": "",
              "id": 246,
              "meta": "{ \"title\": \"新建收款单\", \"icon\": \"form\", \"roles\": [\"service_finance\"] }",
              "name": "newreceivableDelivery",
              "order": 1,
              "outLinkUrl": "",
              "parentCode": "receivableDelivery",
              "path": "newreceivable",
              "redirect": "",
              "sysCode": "receivableDelivery",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "receivablelistDelivery",
              "component": "receivable/receivablelist",
              "hidden": "",
              "id": 247,
              "meta": "{ \"title\": \"收款单查询\", \"icon\": \"search\", \"roles\": [ \"service_finance\" ] }",
              "name": "receivablelistDelivery",
              "order": 2,
              "outLinkUrl": "",
              "parentCode": "receivableDelivery",
              "path": "receivablelist",
              "redirect": "",
              "sysCode": "receivableDelivery",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "receivabledetailDelivery",
              "component": "receivable/receivabledetail",
              "hidden": "true",
              "id": 248,
              "meta": "{ \"title\": \"收款单详情\", \"noCache\": true, \"icon\": \"form\", \"roles\": [ \"service_finance\" ] }",
              "name": "receivabledetailDelivery",
              "order": 3,
              "outLinkUrl": "",
              "parentCode": "receivableDelivery",
              "path": "receivabledetail/:ticketno",
              "redirect": "",
              "sysCode": "receivableDelivery",
              "tId": 7
          }
      ],
      "code": "receivableDelivery",
      "component": "Layout",
      "hidden": "",
      "id": 245,
      "meta": "{ \"title\": \"收款管理\", \"icon\": \"tree\", \"roles\": [\"service_finance\"] }",
      "name": "receivableDelivery",
      "order": 28,
      "outLinkUrl": "",
      "parentCode": "",
      "path": "/receivable",
      "redirect": "/receivable/newreceivable",
      "sysCode": "receivableDelivery",
      "tId": 7
  },
  {
      "alwaysShow": "",
      "children": [
          {
              "alwaysShow": "",
              "code": "newinputinvoiceDelivery",
              "component": "invoice/inputinvoice/newinputinvoice",
              "hidden": "",
              "id": 251,
              "meta": "{ \"title\": \"新建进项发票\", \"icon\": \"form\", \"roles\": [ \"service_finance\" ] }",
              "name": "newinputinvoiceDelivery",
              "order": 1,
              "outLinkUrl": "",
              "parentCode": "inputinvoiceDelivery",
              "path": "newinputinvoice",
              "redirect": "",
              "sysCode": "inputinvoiceDelivery",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "inputinvoicelistDelivery",
              "component": "invoice/inputinvoice/inputinvoicelist",
              "hidden": "",
              "id": 252,
              "meta": "{ \"title\": \"进项发票查询\", \"icon\": \"search\", \"roles\": [ \"service_finance\" ] }",
              "name": "inputinvoicelistDelivery",
              "order": 2,
              "outLinkUrl": "",
              "parentCode": "inputinvoiceDelivery",
              "path": "inputinvoicelist",
              "redirect": "",
              "sysCode": "inputinvoiceDelivery",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "inputinvoicedetailDelivery",
              "component": "invoice/inputinvoice/inputinvoicedetail",
              "hidden": "true",
              "id": 253,
              "meta": "{ \"title\": \"进项发票详情\", \"noCache\": true, \"icon\": \"form\", \"roles\": [ \"service_finance\" ] }",
              "name": "inputinvoicedetailDelivery",
              "order": 3,
              "outLinkUrl": "",
              "parentCode": "inputinvoiceDelivery",
              "path": "inputinvoicedetail/:ticketno",
              "redirect": "",
              "sysCode": "inputinvoiceDelivery",
              "tId": 7
          }
      ],
      "code": "inputinvoiceDelivery",
      "component": "Layout",
      "hidden": "",
      "id": 250,
      "meta": "{ \"title\": \"进项发票\", \"icon\": \"tree\", \"roles\": [ \"service_finance\" ] }",
      "name": "inputinvoiceDelivery",
      "order": 29,
      "outLinkUrl": "",
      "parentCode": "",
      "path": "/invoice/inputinvoice",
      "redirect": "/invoice/inputinvoice/newinputinvoice",
      "sysCode": "inputinvoiceDelivery",
      "tId": 7
  },
  {
      "alwaysShow": "",
      "children": [
          {
              "alwaysShow": "",
              "code": "newoutputinvoiceDelivery",
              "component": "invoice/outputinvoice/newoutputinvoice",
              "hidden": "",
              "id": 255,
              "meta": "{ \"title\": \"申请销项发票\", \"icon\": \"form\", \"roles\": [ \"service_finance\" ] }",
              "name": "newoutputinvoiceDelivery",
              "order": 1,
              "outLinkUrl": "",
              "parentCode": "outputinvoiceDelivery",
              "path": "newoutputinvoice",
              "redirect": "",
              "sysCode": "outputinvoiceDelivery",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "outputinvoicelistDelivery",
              "component": "invoice/outputinvoice/outputinvoicelist",
              "hidden": "",
              "id": 256,
              "meta": "{ \"title\": \"开票申请查询\", \"icon\": \"search\", \"roles\": [ \"service_finance\" ] }",
              "name": "outputinvoicelistDelivery",
              "order": 2,
              "outLinkUrl": "",
              "parentCode": "outputinvoiceDelivery",
              "path": "outputinvoicelist",
              "redirect": "",
              "sysCode": "outputinvoiceDelivery",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "outputinvoiceresultlistDelivery",
              "component": "invoice/outputinvoice/outputinvoiceresultlist",
              "hidden": "",
              "id": 257,
              "meta": "{ \"title\": \"开票结果查询\", \"icon\": \"search\", \"roles\": [ \"service_finance\" ] }",
              "name": "outputinvoiceresultlistDelivery",
              "order": 3,
              "outLinkUrl": "",
              "parentCode": "outputinvoiceDelivery",
              "path": "outputinvoiceresultlist",
              "redirect": "",
              "sysCode": "outputinvoiceDelivery",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "outputinvoicedetailDelivery",
              "component": "invoice/outputinvoice/outputinvoicedetail",
              "hidden": "true",
              "id": 258,
              "meta": "{ \"title\": \"销项开票申请详情\", \"icon\": \"form\", \"noCache\": true, \"roles\": [ \"service_finance\" ] }",
              "name": "outputinvoicedetailDelivery",
              "order": 4,
              "outLinkUrl": "",
              "parentCode": "outputinvoiceDelivery",
              "path": "outputinvoicedetail/:ticketno",
              "redirect": "",
              "sysCode": "outputinvoiceDelivery",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "outputinvoiceresultdetailDelivery",
              "component": "invoice/outputinvoice/outputinvoiceresultdetail",
              "hidden": "true",
              "id": 259,
              "meta": "{ \"title\": \"销项开票详情\", \"icon\": \"form\", \"noCache\": true, \"roles\": [ \"service_finance\" ] }",
              "name": "outputinvoiceresultdetailDelivery",
              "order": 5,
              "outLinkUrl": "",
              "parentCode": "outputinvoiceDelivery",
              "path": "outputinvoiceresultdetail/:ticketno",
              "redirect": "",
              "sysCode": "outputinvoiceDelivery",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "makeoutinvoiceDelivery",
              "component": "invoice/outputinvoice/makeoutinvoice",
              "hidden": "true",
              "id": 260,
              "meta": "{ \"title\": \"财务开票\", \"icon\": \"form\", \"roles\": [ \"service_finance\" ] }",
              "name": "makeoutinvoiceDelivery",
              "order": 6,
              "outLinkUrl": "",
              "parentCode": "outputinvoiceDelivery",
              "path": "makeoutinvoice/:ticketno",
              "redirect": "",
              "sysCode": "outputinvoiceDelivery",
              "tId": 7
          }
      ],
      "code": "outputinvoiceDelivery",
      "component": "Layout",
      "hidden": "",
      "id": 254,
      "meta": "{ \"title\": \"销项发票\", \"icon\": \"tree\", \"roles\": [ \"service_finance\" ] }",
      "name": "outputinvoiceDelivery",
      "order": 30,
      "outLinkUrl": "",
      "parentCode": "",
      "path": "/invoice/outputinvoice",
      "redirect": "/invoice/outputinvoice/newoutputinvoice",
      "sysCode": "outputinvoiceDelivery",
      "tId": 7
  },
  {
      "alwaysShow": "",
      "children": [
          {
              "alwaysShow": "",
              "code": "businessorder",
              "component": "outgoing/businessorder/index",
              "hidden": "",
              "id": 262,
              "meta": "{ \"title\": \"出库业务单\", \"noCache\": true }",
              "name": "businessorder",
              "order": 1,
              "outLinkUrl": "",
              "parentCode": "outgoing",
              "path": "businessorder",
              "redirect": "",
              "sysCode": "outgoing",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "businessorder-detail",
              "component": "outgoing/businessorder/detail",
              "hidden": "true",
              "id": 263,
              "meta": "{ \"title\": \"出库业务单详情\", \"noCache\": true }",
              "name": "businessorder-detail",
              "order": 2,
              "outLinkUrl": "",
              "parentCode": "outgoing",
              "path": "businessorder-detail",
              "redirect": "",
              "sysCode": "outgoing",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "plan",
              "component": "outgoing/plan/index",
              "hidden": "",
              "id": 264,
              "meta": "{ \"title\": \"出库计划\", \"noCache\": true }",
              "name": "plan",
              "order": 3,
              "outLinkUrl": "",
              "parentCode": "outgoing",
              "path": "plan",
              "redirect": "",
              "sysCode": "outgoing",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "plan-detail",
              "component": "outgoing/plan/detail",
              "hidden": "true",
              "id": 265,
              "meta": "{ \"title\": \"出库计划详情\", \"noCache\": true }",
              "name": "plan-detail",
              "order": 4,
              "outLinkUrl": "",
              "parentCode": "outgoing",
              "path": "plan-detail",
              "redirect": "",
              "sysCode": "outgoing",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "quiry",
              "component": "outgoing/quiry/index",
              "hidden": "",
              "id": 267,
              "meta": "{ \"title\": \"出库单查询\", \"noCache\": true }",
              "name": "quiry",
              "order": 5,
              "outLinkUrl": "",
              "parentCode": "outgoing",
              "path": "quiry",
              "redirect": "",
              "sysCode": "outgoing",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "quiry-detail",
              "component": "outgoing/quiry/detail",
              "hidden": "true",
              "id": 268,
              "meta": "{ \"title\": \"出库单查询详情\", \"noCache\": true }",
              "name": "quiry-detail",
              "order": 6,
              "outLinkUrl": "",
              "parentCode": "outgoing",
              "path": "quiry-detail",
              "redirect": "",
              "sysCode": "outgoing",
              "tId": 7
          }
      ],
      "code": "outgoing",
      "component": "Layout",
      "hidden": "",
      "id": 261,
      "meta": "{ \"title\": \"出库调度\", \"noCache\": true, \"icon\": \"out\" }",
      "name": "outgoing",
      "order": 31,
      "outLinkUrl": "",
      "parentCode": "",
      "path": "/outgoing",
      "redirect": "outgoing/businessorder",
      "sysCode": "outgoing",
      "tId": 7
  },
  {
      "alwaysShow": "",
      "children": [
          {
              "alwaysShow": "",
              "code": "warehousing-businessorder",
              "component": "warehousing/businessorder/index",
              "hidden": "",
              "id": 270,
              "meta": "{ \"title\": \"入库业务单\", \"noCache\": true }",
              "name": "warehousing-businessorder",
              "order": 1,
              "outLinkUrl": "",
              "parentCode": "warehousing",
              "path": "businessorder",
              "redirect": "",
              "sysCode": "warehousing",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "warehousing-businessorder-detail",
              "component": "warehousing/businessorder/detail",
              "hidden": "true",
              "id": 271,
              "meta": "{ \"title\": \"入库业务单详情\", \"noCache\": true }",
              "name": "warehousing-businessorder-detail",
              "order": 2,
              "outLinkUrl": "",
              "parentCode": "warehousing",
              "path": "businessorder-detail",
              "redirect": "",
              "sysCode": "warehousing",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "warehousing-plan",
              "component": "warehousing/plan/index",
              "hidden": "",
              "id": 272,
              "meta": "{ \"title\": \"入库计划\", \"noCache\": true }",
              "name": "warehousing-plan",
              "order": 3,
              "outLinkUrl": "",
              "parentCode": "warehousing",
              "path": "plan",
              "redirect": "",
              "sysCode": "warehousing",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "warehousing-plan-detail",
              "component": "warehousing/plan/detail",
              "hidden": "true",
              "id": 274,
              "meta": "{ \"title\": \"入库计划详情\", \"noCache\": true }",
              "name": "warehousing-plan-detail",
              "order": 4,
              "outLinkUrl": "",
              "parentCode": "warehousing",
              "path": "plan-detail",
              "redirect": "",
              "sysCode": "warehousing",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "warehousing-quiry",
              "component": "warehousing/quiry/index",
              "hidden": "",
              "id": 275,
              "meta": "{ \"title\": \"入库单查询\", \"noCache\": true }",
              "name": "warehousing-quiry",
              "order": 5,
              "outLinkUrl": "",
              "parentCode": "warehousing",
              "path": "quiry",
              "redirect": "",
              "sysCode": "warehousing",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "warehousing-quiry-detail",
              "component": "warehousing/quiry/detail",
              "hidden": "true",
              "id": 276,
              "meta": "{ \"title\": \"入库单查询详情\", \"noCache\": true }",
              "name": "warehousing-quiry-detail",
              "order": 6,
              "outLinkUrl": "",
              "parentCode": "warehousing",
              "path": "quiry-detail",
              "redirect": "",
              "sysCode": "warehousing",
              "tId": 7
          }
      ],
      "code": "warehousing",
      "component": "Layout",
      "hidden": "",
      "id": 269,
      "meta": "{ \"title\": \"入库调度\", \"noCache\": true, \"icon\": \"in\" }",
      "name": "warehousing",
      "order": 32,
      "outLinkUrl": "",
      "parentCode": "",
      "path": "/warehousing",
      "redirect": "warehousing/businessorder",
      "sysCode": "warehousing",
      "tId": 7
  },
  {
      "alwaysShow": "",
      "children": [
          {
              "alwaysShow": "",
              "code": "inventory-quiry",
              "component": "inventory/quiry/index",
              "hidden": "",
              "id": 278,
              "meta": "{ \"title\": \"库存查询\", \"noCache\": true }",
              "name": "inventory-quiry",
              "order": 1,
              "outLinkUrl": "",
              "parentCode": "inventory",
              "path": "quiry",
              "redirect": "",
              "sysCode": "inventory",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "inventory-quiry-detail",
              "component": "inventory/quiry/detail",
              "hidden": "true",
              "id": 279,
              "meta": "{ \"title\": \"库存查询详情\", \"noCache\": true }",
              "name": "inventory-quiry-detail",
              "order": 2,
              "outLinkUrl": "",
              "parentCode": "inventory",
              "path": "quiry-detail",
              "redirect": "",
              "sysCode": "inventory",
              "tId": 7
          }
      ],
      "code": "inventory",
      "component": "Layout",
      "hidden": "",
      "id": 277,
      "meta": "{ \"title\": \"库存管理\", \"noCache\": true, \"icon\": \"plan\" }",
      "name": "inventory",
      "order": 33,
      "outLinkUrl": "",
      "parentCode": "",
      "path": "/inventory",
      "redirect": "inventory/quiry",
      "sysCode": "inventory",
      "tId": 7
  },
  {
      "alwaysShow": "",
      "children": [
          {
              "alwaysShow": "",
              "code": "owerinfo",
              "component": "businessset/owerinfo/index",
              "hidden": "",
              "id": 281,
              "meta": "{ \"title\": \"货主信息\", \"noCache\": true }",
              "name": "owerinfo",
              "order": 1,
              "outLinkUrl": "",
              "parentCode": "businessset",
              "path": "owerinfo",
              "redirect": "",
              "sysCode": "businessset",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "owerinfo-detail",
              "component": "businessset/owerinfo/detail",
              "hidden": "true",
              "id": 282,
              "meta": "{ \"title\": \"货主信息详情\", \"noCache\": true }",
              "name": "owerinfo-detail",
              "order": 2,
              "outLinkUrl": "",
              "parentCode": "businessset",
              "path": "owerinfo-detail",
              "redirect": "",
              "sysCode": "businessset",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "customerconfiguration",
              "component": "businessset/customerconfiguration/index",
              "hidden": "",
              "id": 283,
              "meta": "{ \"title\": \"客户仓库关系配置\", \"noCache\": true }",
              "name": "customerconfiguration",
              "order": 3,
              "outLinkUrl": "",
              "parentCode": "businessset",
              "path": "customerconfiguration",
              "redirect": "",
              "sysCode": "businessset",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "customerconfiguration-detail",
              "component": "businessset/customerconfiguration/detail",
              "hidden": "true",
              "id": 284,
              "meta": "{ \"title\": \"客户仓库关系配置详情\", \"noCache\": true }",
              "name": "customerconfiguration-detail",
              "order": 4,
              "outLinkUrl": "",
              "parentCode": "businessset",
              "path": "customerconfiguration-detail",
              "redirect": "",
              "sysCode": "businessset",
              "tId": 7
          }
      ],
      "code": "businessset",
      "component": "Layout",
      "hidden": "",
      "id": 280,
      "meta": "{ \"title\": \"业务设置\", \"noCache\": true, \"icon\": \"busyness\" }",
      "name": "businessset",
      "order": 34,
      "outLinkUrl": "",
      "parentCode": "",
      "path": "/businessset",
      "redirect": "businessset/configuration",
      "sysCode": "businessset",
      "tId": 7
  },
  {
      "alwaysShow": "",
      "children": [
          {
              "alwaysShow": "",
              "code": "reply-query",
              "component": "reply/query/index",
              "hidden": "",
              "id": 286,
              "meta": "{ \"title\": \"回单查询\", \"noCache\": true }",
              "name": "reply-query",
              "order": 1,
              "outLinkUrl": "",
              "parentCode": "reply",
              "path": "query",
              "redirect": "",
              "sysCode": "reply",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "reply-newreceiptorder-detail",
              "component": "reply/newreceiptorder/detail",
              "hidden": "true",
              "id": 287,
              "meta": "{ \"title\": \"回单详情\", \"noCache\": true }",
              "name": "reply-newreceiptorder-detail",
              "order": 2,
              "outLinkUrl": "",
              "parentCode": "reply",
              "path": "newreceiptorder-detail",
              "redirect": "",
              "sysCode": "reply",
              "tId": 7
          },
          {
              "alwaysShow": "",
              "code": "reply-newreceiptorder",
              "component": "reply/newreceiptorder/index",
              "hidden": "true",
              "id": 291,
              "meta": "{ \"title\": \"创建回单\", \"noCache\": true }",
              "name": "reply-newreceiptorder",
              "order": 3,
              "outLinkUrl": "",
              "parentCode": "reply",
              "path": "newreceiptorder",
              "redirect": "",
              "sysCode": "reply",
              "tId": 7
          }
      ],
      "code": "reply",
      "component": "Layout",
      "hidden": "",
      "id": 285,
      "meta": "{ \"title\": \"回单管理\", \"noCache\": true, \"icon\": \"back\" }",
      "name": "reply",
      "order": 35,
      "outLinkUrl": "",
      "parentCode": "",
      "path": "/reply",
      "redirect": "reply/query",
      "sysCode": "reply",
      "tId": 7
  }
]